# Generated by Django 6.1.1 on 2026-10-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payment_stripe_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_session_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
